"""
Django settings for DRFSO2_Test project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-b3iwtm=g!*#$23y+brrpt(=3*3n51upp2%zmaz7746ghoufc#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # test
    'oauth2_provider',
    'social.apps.django_app.default',
    'rest_framework_social_oauth2',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'DRFSO2_Test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + "/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'DRFSO2_Test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
}

AUTHENTICATION_BACKENDS = (

    # Github OAuth2
    'social.backends.github.GithubOAuth2',
    # Local OAuth2
   'DRFSO2_Test.LocalOAuth2.LocalOAuth2',
   'rest_framework_social_oauth2.backends.DjangoOAuth2',

   'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    # 'social.pipeline.mail.mail_validation',
    # 'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
    # Local step
    'DRFSO2_Test.auth_pipeline.redirect_with_access_token'
)

# This is a url name (used with reverse(url_name)) used in the custom pipeline step : 'DRFSO2_Test.auth_pipeline.redirect_with_access_token'
# to determine on which url add access_token, backend, expires as parameters
# and check whether login procudere final redirection is going to this url
REDIRECT_WITH_ACCESS_TOKEN_URL_NAME = 'profile'



# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

SOCIAL_AUTH_DJANGO_KEY="pzPkzqi8haK3ob96ff8RxSqIzrvWoq3PzZMuv3Us"
SOCIAL_AUTH_DJANGO_SECRET="i37vk0FDkQF41fCOWXBuJ7zc3KSLpyRofLACn0hApXjWUjcGbjoDkHYXMqptNE4K1IFDPtS7elzc0ysWDPGaakPHzywYHTWivzXzE2teQYN5BlIm7pxyZOxxsCt8HAGR"

SOCIAL_AUTH_LOCALOAUTH2_KEY="pzPkzqi8haK3ob96ff8RxSqIzrvWoq3PzZMuv3Us"
SOCIAL_AUTH_LOCALOAUTH2_SECRET="i37vk0FDkQF41fCOWXBuJ7zc3KSLpyRofLACn0hApXjWUjcGbjoDkHYXMqptNE4K1IFDPtS7elzc0ysWDPGaakPHzywYHTWivzXzE2teQYN5BlIm7pxyZOxxsCt8HAGR"

# Github configuration
SOCIAL_AUTH_GITHUB_KEY = 'd8b005cb7f3a27b4d7f7'
SOCIAL_AUTH_GITHUB_SECRET = 'a68c6b3a291414de4fabd119ad85ee5c576603fd'

LOCALOAUTH2_API_URL = 'http://127.0.0.1:8000'